apiVersion: v1
kind: Secret
metadata:
  name: test-app-secret
  namespace: appspace
type: Opaque
stringData:
  JWT_SECRET: haevhvsdchvjkbhvsdHCvmhdCdCNBhavjhvakjahbs,hjasvCjvasHCvhasVChasvNvasHCV
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: api_gateway
